### ISSUE TITLE
register_asset_bundle

### ISSUE THREAD

**Issue by bubasuma** [yiisoft/yii2-twig#43] opened 2016-01-07 17:32 UTC
Why this function is not returning a value? 
```php
    // yii\twig\Extension.php
    public function registerAssetBundle($context, $bundle)
    {
        $bundle = str_replace('/', '\\', $bundle);
        $this->call($bundle, 'register', [
            isset($context['this']) ? $context['this'] : null,
        ]);
    }
```
What if i will need to use it in my view? like this
```php
$asset = AppAsset::register($this);
echo $asset->baseUrl
```

**Comment by samdark** [comment] 2016-01-07 18:45
Duplicate of https://github.com/yiisoft/yii2-twig/issues/40

**Closed by samdark** 2016-01-07 18:45 UTC
Labels: bug
